config/routes.rb
Ec2Cost::Application.routes.draw do
  resources :pages

  root :to => 'pages#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
require File.expand_path('../../../lib/aws_price', __FILE__)

class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    awc = AWSPrice.new
    @rate = awc.rate

    costs_st = awc.calc_cost :small => 0.1, :large => 0.4, :extra_large => 0.8 
    costs_mic = awc.calc_cost :micro => 0.027 
    costs_h_mem = awc.calc_cost :extra_large => 0.60, :double_extra_large => 1.2, :quad_extra_large => 2.39
    costs_h_cpu = awc.calc_cost :medium => 0.2, :extra_large => 0.8

    @costs = {"Standard" => costs_st, 
              "Micro" => costs_mic, 
              "High Memory" => costs_h_mem, 
              "High CPU" => costs_h_cpu}
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ec2Cost</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Amazon EC2 cost</h1>
<h2>1ヶ月当たり(31日分)のAmazon EC2の価格を日本円で表示します。</h2>
<h3>Asia Pacific Tokyo </h3>

Rate:
1米ドル = 
<%= number_to_currency(@rate, :unit => "円", :precision => 2, :format => '%n%u') %>
<br>
<br>


<% @costs.each do |key, val_cost| %>
  <table>
  <th>
    <%= key %>
  </th>
  <% val_cost.each do |c| %>
    <tr>
      <td><%= c[0] %></td>
      <td><%= number_to_currency(c[1], :unit => "円", :precision => 0, :format => '%n%u') %></td>
    </tr>
  <% end %>
  </table>
  <br>
<% end %>

2011 @u16suzu
<br>
<br>
<!--タグはここから--><table border="0" cellspacing="0" cellpadding="0"><tr><td align="center"><a href="http://www.rays-counter.com/"><img src="http://www.rays-counter.com/d140_f6_001/4eff4b20865e0/" alt="アクセスカウンター" border="0"></a></td></tr><tr><td align="center"><a href="http://auve.jp/"><img src="http://www.rays-counter.com/images/counter_01.gif" border="0" alt="占い"></a><a href="http://www.e-creditcard.info/"><img src="http://www.rays-counter.com/images/counter_02.gif" border="0" alt="クレジットカード比較"></a><a href="http://angeldays.jp/"><img src="http://www.rays-counter.com/images/counter_03.gif" border="0" alt="おっきくなぁれ 販売"></a><a href="http://www.queen-eyes.com/fs/queeneyes/c/black/"><img src="http://www.rays-counter.com/images/counter_04.gif" border="0" alt="カラコン 黒"></a><img src="http://www.rays-counter.com/images/counter_05.gif" border="0"></td></tr></table><!--ここまで-->

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>